### ISSUE TITLE
Kinesis request metrics

### ISSUE THREAD

**Issue by damianbl** [bizreach/aws-kinesis-scala#10]
Hi,

I am thinking about possibility to set `RequestMetricCollector`. I saw that you use implicit conversion for converting your request into AWS request. So I think it would be possible to add the collector to PutRecordRequest and then use in the conversion.
What do you think?

I can create a PR for this.

**Comment by shimamoto** [comment]
Oh Cool! We welcome your PR anytime :)

**Comment by damianbl** [comment]
Cool. Can you let me push the branch to your repo? Thank you.

**Comment by shimamoto** [comment]
I'm sorry, but please fork our repository and send pull request from your repository.

**Comment by damianbl** [comment]
That's perfectly fine. I'll do it. Thanks.

**Comment by shimamoto** [comment]
@damianbl Merged #11. Thanks!

**Comment by damianbl** [comment]
I thank you. Now I can look into the metrics.
